url: "https://danielcoderx.github.io/crystal_with_dx/"
baseurl: "/crystal_with_dx"
title: "Crystal With DX"
author: "DX"
description: "A community-driven platform dedicated to learning and exploring the Crystal programming language."
email: "danyalghlaby@gmail.com"
twitter_username: "danielcoderx"
github_username: "danielcoderx"
