url: "http://github.com/danielcoderx"
baseurl: "/"
title: "Crystal With DX"
author: "DX"
description: "A community-driven platform dedicated to learning and exploring the Crystal programming language."
email: "danyalghlaby@gmail.com"
twitter_username: "danielcoderx"
github_username: "danielcoderx"
